// <auto-generated />
using FlatBrowser.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlatBrowser.Migrations
{
    [DbContext(typeof(FlatBrowserDBContext))]
    [Migration("20201014170529_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("FlatBrowser.Models.FileExtension", b =>
                {
                    b.Property<int>("FileExtensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FileExtensionId", "FolderCategoryId");

                    b.HasIndex("FolderCategoryId");

                    b.ToTable("FileExtensions");
                });

            modelBuilder.Entity("FlatBrowser.Models.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId", "FolderCategoryId");

                    b.HasIndex("FolderCategoryId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("FlatBrowser.Models.FolderCategory", b =>
                {
                    b.Property<int>("FolderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderCategoryId");

                    b.ToTable("FolderCategories");
                });

            modelBuilder.Entity("FlatBrowser.Models.FileExtension", b =>
                {
                    b.HasOne("FlatBrowser.Models.FolderCategory", null)
                        .WithMany("Extensions")
                        .HasForeignKey("FolderCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlatBrowser.Models.Folder", b =>
                {
                    b.HasOne("FlatBrowser.Models.FolderCategory", "FolderCategory")
                        .WithMany("Folders")
                        .HasForeignKey("FolderCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
