// <auto-generated />
using System;
using FlatBrowser.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlatBrowser.Migrations
{
    [DbContext(typeof(FlatBrowserDBContext))]
    partial class FlatBrowserDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("FlatBrowser.Models.FileExtension", b =>
                {
                    b.Property<int>("FileExtensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FolderCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FileExtensionId");

                    b.HasIndex("FolderCategoryId");

                    b.ToTable("FileExtension");
                });

            modelBuilder.Entity("FlatBrowser.Models.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FolderCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId");

                    b.HasIndex("FolderCategoryId");

                    b.ToTable("Folder");
                });

            modelBuilder.Entity("FlatBrowser.Models.FolderCategory", b =>
                {
                    b.Property<int>("FolderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderCategoryId");

                    b.ToTable("FolderCategories");
                });

            modelBuilder.Entity("FlatBrowser.Models.FileExtension", b =>
                {
                    b.HasOne("FlatBrowser.Models.FolderCategory", null)
                        .WithMany("Extensions")
                        .HasForeignKey("FolderCategoryId");
                });

            modelBuilder.Entity("FlatBrowser.Models.Folder", b =>
                {
                    b.HasOne("FlatBrowser.Models.FolderCategory", "FolderCategory")
                        .WithMany("Folders")
                        .HasForeignKey("FolderCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
